### ISSUE TITLE
MSBuild names are translated in translated docs

### ISSUE THREAD

**Issue by cartermp** [NuGet/docs.microsoft.com-nuget.ru-ru#27]
See here: https://docs.microsoft.com/ru-ru/nuget/reference/msbuild-targets

<img width="947" alt="screen shot 2018-07-20 at 07 48 52" src="https://user-images.githubusercontent.com/6309070/43009099-913aecda-8bf1-11e8-8681-13563e7d70d5.png">

It's easy to tell that it is incorrect for some languages, but in others, it can be a bit more subtle: https://docs.microsoft.com/es-es/nuget/reference/msbuild-targets

"Versión" is listed as a nuspec value, but I'm pretty sure MSBuild won't know what to do with that.

**Comment by srvbpigh** [comment]
Hello, @cartermp
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello @cartermp 

Thank you for your contribution. 

Contributions on translation problems against machine-translated content are currently not accepted. 

We value your feedback and suggestions on human translated content, which is used to train the machine translation engines, so over time, your contributions will improve the quality of both human and machine translations. 

Human translated topics can be distinguished from machine-translated topics by the ms.translationtype metadata value “HT” (versus “MT” for machine translated) in the header of each content file. 

Many thanks for your support. 

Microsoft DOCS Global Experience Team 

@JasonCard #please-close

**Comment by JasonCard** [comment]
Hi @cartermp ,
Thank you for your feedback.
It's difficult for Machine Translation to not over-localize certain terms, so I've requested the writing team for help to block these terms from localization [#2006](https://github.com/NuGet/docs.microsoft.com-nuget/issues/2006).

Best regards,
Jason

**Comment by CeciAc** [comment]
#please-close
