### ISSUE TITLE
Where is 'IncludeSource' option in snupkg package

### ISSUE THREAD

**Issue by AlexeiScherbakov** [NuGet/docs.microsoft.com-nuget.ru-ru#7]
Where is 'IncludeSource' option in snupkg package?

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 22767e96-d56f-aa81-f1ca-17e256ed617e
* Version Independent ID: d7cdc676-2705-3cb1-bcd6-d1637460d5c7
* Content: [Публикация пакетов символов NuGet с помощью нового формата, SNUPKG](https://docs.microsoft.com/ru-ru/nuget/create-packages/symbol-packages-snupkg)
* Content Source: [docs/create-packages/Symbol-Packages-snupkg.md](https://github.com/NuGet/docs.microsoft.com-nuget.ru-ru/blob/live/docs/create-packages/Symbol-Packages-snupkg.md)
* Product: **nuget**
* Technology: ****
* GitHub Login: @olprod
* Microsoft Alias: **cristinamanu**

**Comment by CeciAc** [comment]
Hello, @AlexeiScherbakov 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
